### PR TITLE
Exclude setGroupingSize test from both Hotspot and OpenJ9 on JDK14+

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
The change made in https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/329 will exclude DecimalFormat.setGroupingSize from 8 and 11.  

However, https://bugs.openjdk.java.net/browse/JDK-8231851 applies to jdk versions 14+

This PR reverts https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/329, and adds excludes the exclude files specific to 14+ runs of this test, and removes the check for openj9 from the mauve stf wrapper code.  

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test OpenJ9 JDK 14: Test_grinder/job/Grinder/6266/console

**Comment by Mesbah-Alam** [comment]
@JasonFengJ9 - FYI.

**Comment by lumpfish** [comment]
I don't think it's worth putting in code which says 'if > jdkn' as conditionals for running these tests, or creating specific exclude files.  The maintenance overhead is just too great.  The life of the mauve test suite is limited anyway - it has not been maintained for 10 years.  Rather than creating more config files I would advocate removing release (and jvm) specific config files and just run with the lowest common denominator of tests across all releases.

**Comment by pshipton** [comment]
https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/330#issuecomment-591884003 is fine with me.

**Comment by Mesbah-Alam** [comment]
Sounds Good. I've created an issue to clean up Mauve tests and have a single load across all platforms and sdk versions https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/331. 

Closing this PR without merging.

**Pull request closed without merging**
