### PR TITLE
Remove dependency of ant-contrib <if> tag from openjdk.test.debugging project 

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/405

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test: 
  - with JDK8 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6689/
  - with JDK 11 :  https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6688/

**Review by lumpfish — APPROVED** [review]
Looks good

**Comment by Mesbah-Alam** [comment]
Test with JDK 17 : internal-Grinder/13846

**Review by llxia — APPROVED** [review]
LGTM

**Review by zijwij-byxmyq-1wIxre — COMMENTED** [review]
Ddd

**Pull request merged**
