### PR TITLE
Fix HCRLateAttachWorkload_previewEnabled failure on jdk17

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Change asm to jvm asm for jdk 15+
- Related Issue: https://github.com/eclipse/openj9/issues/11642
- Need to merge with PR (https://github.com/AdoptOpenJDK/openjdk-tests/pull/2208) together.

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Links:
jdk8: 
- xlinux, zlinux, mac, aix, win: openj9 (13464); hotspot (13470)   
- aarch: openj9 and hotspot (Adopt 6099)

jdk11,15,16: 
- xlinux, zlinux, mac, aix, win:  openj9 (13476 with passed rerun grinder 13479->13520 and 13482->13515); hotspot (13492 with passed rerun grinder 13499->13517)  
- aarch: openj9 and hotspot (Adopt 6102)

jdk17: 
- openj9: xlinux: 13513 zlinux: 13509   mac: 13510   aix: 13511  win:13512

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks for the rework on this @LongyuZhang !

**Review by zijwij-byxmyq-1wIxre — COMMENTED** [review]
Ddd

**Pull request merged**
