### PR TITLE
Update BigDecimal Tests for JDK13

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/259

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Background: 

There has been made a deliberate change in JDK13 in movePointRight():

JDK 13:
https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/0bcd1d5bd66ca25fba18a7bbf5003a395470d4fe/src/java.base/share/classes/java/math/BigDecimal.java#L2903-L2909

JDK 12:
https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/b26359aebe7ec913c0abdac75fb6abe21ed28cf0/src/java.base/share/classes/java/math/BigDecimal.java#L2901-L2905

https://bugs.openjdk.java.net/browse/JDK-8183912

This PR updates the tests that use .movePointRight(0) to return the same string as passed in when we are using JDK13 and up.

**Comment by Mesbah-Alam** [comment]
movePointLeft() was also updated in JDK13. So, I'll update the tests that use that API as well.

JDK13:
https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/0bcd1d5bd66ca25fba18a7bbf5003a395470d4fe/src/java.base/share/classes/java/math/BigDecimal.java#L2879

JDK12:
https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/b26359aebe7ec913c0abdac75fb6abe21ed28cf0/src/java.base/share/classes/java/math/BigDecimal.java#L2879

**Comment by llxia** [comment]
Is it possible to use existing API to get java version?
https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/89ed48fb3ee763b6559d7802648c8431429d6d25/openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ClassloadingLoadTest.java#L50

**Comment by Mesbah-Alam** [comment]
@llxia - I thought about using the existing API to get the Java version. But the reason why I didn't do that is because, then we'd have to pass in an instance of `StfCoreExtensionc` into these Junit test classes who don't have any reference to StfCoreExtension by default, and who are not invoked directly from any class who instantiate StfCoreExtension either. So, It seemed more work than necessary to use existing APIs and I created a simple class to get the vm spec version instead.

**Comment by llxia** [comment]
Thanks @Mesbah-Alam for testing against openj9 and hotspot in Grinder.

**Pull request merged**
