### PR TITLE
Adjust jlm load parameters

### PR DESCRIPTION
**Pull request by lumpfish**
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Are we increasing the timeout for these tests for allowing these tests to work normally on slow platforms (e.g. ones without JIT, etc)?

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]

**Comment by lumpfish** [comment]
The tests passed on last night's builds following the merge.  Raised https://github.com/eclipse/openj9-systemtest/pull/118 to do the same for the openj9 specific jlm tests.

**Comment by lumpfish** [comment]
See https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/360 for failure analysis

**Pull request merged**
