### PR TITLE
Update systemtest to build on Java 11

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/148
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by karianna** [comment]
What happens with Java 12 :-)

**Comment by lumpfish** [comment]
"What happens with Java 12 :-)".
 If (when?) using -classpath becomes invalid the tests would no longer be able to run unless work was done in the mauve project to modularise the tests.  The project doesn't appear to have been active since Java 7.  Other than that tests become invalid when some backward compatibility is removed (e.g. a number of tests were excluded at Java 9 because '_' was no longer supported as an identifier).
The test suite has generally proved useful over the years for finding regressions and as a general workload for finding VM . JIT issues.

**Comment by karianna** [comment]
Thanks for the explanation!  I should have been clearer in my comment.  I was referring to using a property isJava11 which possibly needs to be ifJavaGreaterThan10 or something like that and also pick up on newer versions going forwards every 6 months - might need a regex?.

**Comment by Mesbah-Alam** [comment]
`isJava11` is added to temporarily exclude `test.modularity` project to be built on Java 11. This is added to unblock Java 11 test builds (jck etc) before we come up with the re-implemented modularity test cases. Once PR for https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/150 is delivered, the `isJava11` check will be removed. @karianna

**Pull request merged**
