### PR TITLE
Issue 5 : Integrate system test with testkitgen

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Added top level build file to build all systemtest projects with
testKitGen. Also, added playlist.xml for svt tests 

Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by lumpfish** [comment]
The comment says "Added top level build file to build all systemtest projects with testKitGen".  But I see an openjdk.build/include/build.xml.  Is that the 'top level' file?  Generally, how does the integration with testkitgen occur?

**Comment by Mesbah-Alam** [comment]
Hi Simon, 

In order to integrate openjdk-systemtest with testKitGen, we checkout openjdk-systemtest under openjdk-test as a "project". Since testKitGen requires the build.xml of any "project" to exist inside its folder, in order to build all the svt projects under openjdk-systemtest, we needed a build.xml right under openjdk-systemtest. The function of this build.xml file is to simply invoke the "real" top level svt build file (e.g. openjdk.build/build.xml). 

For lack of a better place to put this new build.xml file, we placed it under openjdk.build/include. The Jenkins build script, as part of setup, copies this build.xml file from openjdk.build/include and places it directly under the openjdk-test/openjdk-systemtest folder during a build. 

If you think it's not the right place for it to be, we can put it somewhere else too. And I should add a top level comment inside the build.xml file itself explaining what it is used for. 

@lumpfish

**Comment by lumpfish** [comment]
Thanks for the clarification.  I think it would be easier to follow if we just put the build.xml into openjdk-systemtest root.
Please could you add a comment to the file along the lines of 'a build.xml which executes the main openjdk.build build.xml to allow tools which invoke a root level build.xml file to execute a build'.

**Comment by Mesbah-Alam** [comment]
The new build.xml has been moved to the root of openjdk-systemtest. Comment has been added. @lumpfish

**Pull request merged**
