### PR TITLE
Fix HCRLateAttachWorkload_previewEnabled failure on jdk17

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Change asm to jvm asm
- Set different Opcodes.ASM versions for jdk 8 and 11+
- Related Issue: https://github.com/eclipse/openj9/issues/11642
- Need to merge with PR (https://github.com/AdoptOpenJDK/openjdk-tests/pull/2182) together.

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Links:

jdk17:  
xlinux: 13275 61 zlinux: 13276   mac: 13277   aix: 13278  win: 13279

jdk16: 
xlinux: 13270   zlinux: 13271   mac: 13272   aix: 13273  win: 13274

jdk8:
xlinux: 13265   zlinux: 13266   mac: 13267   aix: 13268  win: 13269

**Review by smlambert — APPROVED** [review]

**Comment by Mesbah-Alam** [comment]
Please rebase the development branch and accept the latest changes for https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/392 before merging this. PR, just to be on the safe side.

**Review by llxia — APPROVED** [review]

**Comment by LongyuZhang** [comment]
> Please rebase the development branch and accept the latest changes for #392 before merging this PR, just to be on the safe side.

The Commit has been rebased, and passed tests (Grinder 13437-13439 for jdk 8, 16 and 17). Thanks.

**Comment by llxia** [comment]
Thanks @LongyuZhang

**Pull request merged**
