### PR TITLE
Exclude Mauve[gnu.testlet.java.lang.NullPointerException.constructor]

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Exclude Mauve[gnu.testlet.java.lang.NullPointerException.constructor]

related: https://github.com/eclipse/openj9/issues/11206

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
@Mesbah-Alam could you please review?

**Comment by Mesbah-Alam** [comment]
Please move this exclude to [mauve_multiThread_exclude.xml ](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml), from mauve_all_exclude.xml. 

The test that is to be excluded is being run under `MauveMultiThreadLoadTest` - which actually runs a [mauve_multiThread.xml ](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml) load.  

The exclusion mechanism in these STF load tests work in such a way that, if we want a sub-test to be excluded from `mauve_multiThread.xml`, the exclude needs to be listed in `mauve_multiThread_exclude.xml`.

**Comment by JasonFengJ9** [comment]
@Mesbah-Alam the test in question runs within `MauveMultiThreadLoadTest_0` and `MauveSingleThreadLoadTest_OpenJ9_0` as per eclipse/openj9#11206. Does `mauve_multiThread.xml` cover single test mode as well? Do I have to add this test in both `mauve_multiThread_exclude.xml` and `auve_all_exclude.xml`?

**Comment by Mesbah-Alam** [comment]
Hi @JasonFengJ9, 
According to https://github.com/eclipse/openj9/issues/11206 , the test is failing in both MauveMultiThreadLoadTest_0 and MauveSingleThreadLoadTest_OpenJ9_0 targets. So, yes, since `gnu.testlet.java.lang.NullPointerException.constructor` exists in both the load config files, it should be added in both their exclude files in order to confirm this sub-test will not run.

**Comment by JasonFengJ9** [comment]
Thanks @Mesbah-Alam , updated PR accordingly, please have another look.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
The PR looks good. Thanks @JasonFengJ9 . Please merge it whenever it is convenient to you.

**Pull request merged**
