### PR TITLE
Exclude Dateformat.equals test from multithreaded mauve run

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Related to https://github.com/eclipse/openj9/issues/8204

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Doing a search in the mauve source for tests that invoke Locale.setDefault(..) Yields following list. Out of which none are [listed](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml) to run in mauve multithreaded test . Hence the exclude only contains the test that is reported to fail in  https://github.com/eclipse/openj9/issues/8204

```
Mesbahs-MacBook-Pro:mauve-latest Mesbah_Alam@ca.ibm.com$ grep -r Locale.setDefault .
./gnu/testlet/locales/LocaleTest.java:    Locale.setDefault(Locale.GERMAN);
./gnu/testlet/runner/Mauve.java:    Locale.setDefault(savedLocale);
./gnu/testlet/java/util/GregorianCalendar/internal.java:      Locale.setDefault(locale);
./gnu/testlet/java/util/GregorianCalendar/internal.java:	  Locale.setDefault(defaultLocale);
./gnu/testlet/java/util/GregorianCalendar/setFirstDayOfWeek.java:    Locale.setDefault(Locale.GERMANY);
./gnu/testlet/java/util/Currency/Czech.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/France.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/Germany.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/Canada.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/CanadaFrench.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/Slovak.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/PRC.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/Korea.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/China.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/UK.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/Italy.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/Taiwan.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/util/Currency/Japan.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/lang/String/CASE_INSENSITIVE_ORDER.java:    Locale.setDefault(new Locale("tr", ""));
./gnu/testlet/java/lang/String/CASE_INSENSITIVE_ORDER.java:    Locale.setDefault(l);
./gnu/testlet/java/text/MessageFormat/format.java:      Locale.setDefault (loc);
./gnu/testlet/java/text/MessageFormat/parse.java:      Locale.setDefault (loc);
./gnu/testlet/java/text/BreakIterator/lineiter.java:    Locale.setDefault (loc);
./gnu/testlet/java/text/BreakIterator/sentiter.java:    Locale.setDefault (loc);
./gnu/testlet/java/text/BreakIterator/chariter.java:    Locale.setDefault (loc);
./gnu/testlet/java/text/BreakIterator/worditer.java:    Locale.setDefault (loc);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(loc);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(Locale.UK);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(original);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(Locale.UK);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(original);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(Locale.US);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(orig);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(Locale.US);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(orig);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(Locale.US);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(orig);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(Locale.US);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(orig);
./gnu/testlet/java/text/DecimalFormat/PR23996.java:    Locale.setDefault(Locale.US);
./gnu/testlet/java/text/DecimalFormat/PR23996.java:    Locale.setDefault(orig);
./gnu/testlet/java/text/DecimalFormat/toPattern.java:      Locale.setDefault (loc);
./gnu/testlet/java/text/DecimalFormat/MaximumAndMinimumDigits.java:    Locale.setDefault(Locale.US);
./gnu/testlet/java/text/DecimalFormat/MaximumAndMinimumDigits.java:        Locale.setDefault(original);
./gnu/testlet/java/text/DecimalFormat/position.java:      Locale.setDefault (loc);
./gnu/testlet/java/text/DecimalFormat/formatExp.java:      Locale.setDefault (loc);
./gnu/testlet/java/text/DecimalFormat/toPattern14.java:    Locale.setDefault(loc);
./gnu/testlet/java/text/DecimalFormat/constructors.java:    Locale.setDefault(Locale.UK);
./gnu/testlet/java/text/DecimalFormat/constructors.java:    Locale.setDefault(original);
./gnu/testlet/java/text/DecimalFormat/constructors.java:    Locale.setDefault(Locale.UK);
./gnu/testlet/java/text/DecimalFormat/constructors.java:    Locale.setDefault(original);
./gnu/testlet/java/text/DecimalFormat/parse.java:      Locale.setDefault (loc);
./gnu/testlet/java/text/DecimalFormat/applyPattern.java:    Locale.setDefault(Locale.US);
./gnu/testlet/java/text/DecimalFormat/applyPattern.java:    Locale.setDefault(orig);
./gnu/testlet/javax/swing/plaf/basic/BasicFileChooserUI/uninstallStrings.java:    Locale.setDefault(Locale.UK);
./gnu/testlet/javax/swing/plaf/basic/BasicFileChooserUI/installStrings.java:    Locale.setDefault(Locale.UK);
./gnu/testlet/javax/swing/plaf/basic/BasicFileChooserUI/installStrings.java:    Locale.setDefault(Locale.FRANCE);
./gnu/testlet/javax/swing/text/StringContent/removeUndo.java:        java.util.Locale.setDefault(java.util.Locale.US);
./gnu/testlet/javax/swing/text/StringContent/insertUndo.java:        java.util.Locale.setDefault(java.util.Locale.US);
./gnu/testlet/javax/swing/text/StringContent/BadLocationExceptionTest.java:    java.util.Locale.setDefault(java.util.Locale.US);
```

**Comment by Mesbah-Alam** [comment]
@JasonFengJ9 - please review.

**Comment by JasonFengJ9** [comment]
@Mesbah-Alam if I understand https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/352#issuecomment-646312088 correctly, does it mean there is no `Locale.setDefault()` in current multi-threaded tests? and this PR is just to exclude the failing test itself.
If so, it sounds we didn't identify the actual cause of the failure.

**Comment by Mesbah-Alam** [comment]
Yes, so, I suspect we have tests listed in https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml that in turn call some classes in which there are calls to `Locale.setDefault(..)` - for example `DateFormat.equals`. 

In order to find more such cases, a simple text search won't help. We need to likely set tracepoints and run mauve tests in Grinders.

**Comment by JasonFengJ9** [comment]
That makes sense, agreed that a simple text search won't help.

LGTM.

**Comment by Mesbah-Alam** [comment]
This is a 20X grinder that runs `MauveMultiThreadLoadTest_special_25` with with `-Xtrace:iprint=mt,trigger=method{java/util/Locale.setDefault*,jstacktrace}` on Linux x64: 

Test_grinder/job/Grinder/8513/ 

This is a 20X grinder that `runs MauveMultiThreadLoadTest_special_26` with the same trace option: Test_grinder/job/Grinder/8512

Interestingly, none hits any case where Locale.setDefault(..) is invoked. 

@JasonFengJ9

**Comment by pshipton** [comment]
Hmm, this could indicate there really is a bug rather than bad testing.

Jason mentioned the following tests, are these running? If any are running, perhaps the setLocale() only occurs under certain conditions.
./gnu/testlet/java/util/GregorianCalendar/setFirstDayOfWeek.java:    Locale.setDefault(Locale.GERMANY);
./gnu/testlet/java/util/Currency/Japan.java:    Locale.setDefault(TEST_LOCALE);
./gnu/testlet/java/text/DecimalFormat/format.java:    Locale.setDefault(Locale.UK);
./gnu/testlet/javax/swing/plaf/basic/BasicFileChooserUI/installStrings.java:    Locale.setDefault(Locale.FRANCE);

**Comment by Mesbah-Alam** [comment]
> Jason mentioned the following tests, are these running?

I did a check (details in : https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/352#issuecomment-646312088), but did not find any of the tests Jason mentioned to be running as part of the multi-threaded mauve test set.

**Comment by JasonFengJ9** [comment]
Another experiment could be to run the test in question in single thread mode and see if it fails.

Potentially there is another API (or implicit internal way) to change the default locale.

**Comment by Mesbah-Alam** [comment]
> Another experiment could be to run the test in question in single thread mode and see if it fails.

Here's a 20x Grinder for MauveSingleThreadLoadTest_special_25 (runs single-threaded), run with extra option: `-Xtrace:iprint=mt,trigger=method{java/util/Locale.setDefault*,jstacktrace}` - There is no failure: 

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/8521/

**Comment by JasonFengJ9** [comment]
> Test_grinder/job/Grinder/8513/
> This is a 20X grinder that runs MauveMultiThreadLoadTest_special_26 with the same trace option: Test_grinder/job/Grinder/8512
> Interestingly, none hits any case where Locale.setDefault(..) is invoked.

Both grinder 8512 & 8513 passed w/o reproducing the failure, so there is a possibility that these two grinders are not same as those failed tests.
I think we need to see the failure is reproduced along with the extra option enabled.

**Comment by pshipton** [comment]
@Mesbah-Alam can you add the -Xdump option permanently into the test, so if we get another failure in the builds we can see if the dump was triggered?

**Comment by Mesbah-Alam** [comment]
> so there is a possibility that these two grinders are not same as those failed tests.

Can you please explain this further? 

The grinders are supposed to be running the same load tests as those seen to fail in the builds. 
I.o.w, tests and their variations that have been run in the Grinders above (so far) have all been picked from the failed tests mentioned in https://github.com/eclipse/openj9/issues/8204. For example, Grinder 8512 and 8513 both run MauveMulThreadLoadTest but with two different modes. @JasonFengJ9

**Comment by JasonFengJ9** [comment]
> Can you please explain this further?

In reply to the comment above, just to clarify, I don't have any insights. Given the failure occurrence rate in both external/internal jenkins builds, it seems odd that two 20x grinder didn't reproduce a failure.
If the test fails w/o `Locale.setDefault*` invoked, the we might have to come up with another story instead.

**Comment by pshipton** [comment]
FYI https://github.com/eclipse/openj9/issues/8204#issuecomment-662115686, it seems the problem is with TimeZone.setDefault().

**Comment by Mesbah-Alam** [comment]
We get the following hits searching for `TimeZone.setDefault()` in mauve test codebase: 

```
Mesbahs-MacBook-Pro:mauve Mesbah_Alam@ca.ibm.com$ grep -r TimeZone.setDefault .
Binary file ./mauve.jar matches
./gnu/testlet/locales/LocaleTest.java:    TimeZone.setDefault(TimeZone.getTimeZone("GMT"));   
./gnu/testlet/java/util/SimpleTimeZone/inDaylightTime.java:    TimeZone.setDefault(utc);
./gnu/testlet/java/util/SimpleTimeZone/hashCode.java:    TimeZone.setDefault(utc);
./gnu/testlet/java/util/SimpleTimeZone/hasSameRules.java:    TimeZone.setDefault(utc);
./gnu/testlet/java/util/SimpleTimeZone/equals.java:    TimeZone.setDefault(utc);
./gnu/testlet/java/util/Calendar/set.java:    TimeZone.setDefault(stz);
./gnu/testlet/java/util/Calendar/set.java:    TimeZone.setDefault(null);
./gnu/testlet/java/util/TimeZone/setDefault.java:    TimeZone.setDefault(stz);
./gnu/testlet/java/util/TimeZone/setDefault.java:    TimeZone.setDefault(null);
Binary file ./gnu/testlet/java/util/TimeZone/setDefault.class matches
./gnu/testlet/java/util/TimeZone/zdump.java:    TimeZone.setDefault(utc);
./gnu/testlet/java/util/Date/getTimezoneOffset.java:    TimeZone.setDefault(TimeZone.getTimeZone("America/Toronto"));
./gnu/testlet/java/util/Date/getTimezoneOffset.java:    TimeZone.setDefault(TimeZone.getTimeZone("Pacific/Auckland"));
./gnu/testlet/java/util/Date/getTimezoneOffset.java:    TimeZone.setDefault(TimeZone.getTimeZone("Europe/London"));
./gnu/testlet/java/sql/Timestamp/TimestampTest.java:    TimeZone.setDefault(stz);
./gnu/testlet/java/sql/Timestamp/TimestampTest.java:    TimeZone.setDefault(null);
```

**Comment by Mesbah-Alam** [comment]
This PR applies the required excludes : https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/358

**Pull request closed without merging**
