### PR TITLE
Turn off jdwp.VMSuspended in jck8

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
- Related to : https://github.ibm.com/runtimes/JCK8-unzipped/pull/5#issuecomment-15302207

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Reviewer @JasonFengJ9

**Comment by Mesbah-Alam** [comment]
Test: /Test_grinder/job/Grinder/2414/console

**Comment by JasonFengJ9** [comment]
The `jti` file change seems fine. As per our offline conversation, the `jtb` file has to be set with same configuration as well. If the `jtb` file is generated dynamically, the script is required to be modified accordingly.

**Comment by Mesbah-Alam** [comment]
@JasonFengJ9 : Since the option is available in the JTI file, making the change there should be enough. The generated JTB file only is used to override some options dynamically at run time, as the [documentation](https://github.com/AdoptOpenJDK/openjdk-systemtest/tree/master/openjdk.test.jck/docs) suggests: 

> The JCK harness provides a method for the configuration values to be overridden at test execution time
> by redefining values via a jtb file (xxx.jtb) and passing the name of that file to the test harness.
> A number of the values used in the testing are specific to the machine executing the tests. The test automation
> (Jck.java) creates a unique jtb file for each test run, overriding these values with those appropriate
> for the current test machine. The jtb file is placed into a JTB directory within the test run's
> unique results directory. All the test output from the JCK harness itself is also directed to the test results
> directory.

When the jck automation is run in the build, both the JTI and the JTB files are supplied to the process: 

```
11:46:05  STF 11:46:04.939 - Running command: /home/j9build/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -jar /home/j9build/jck_root/JCK8-unzipped/JCK-runtime-8b/lib/jtlite.jar  -config /home/j9build/workspace/Grinder/jvmtest/system/openjdk-systemtest/openjdk.test.jck/config/jck8b/runtime.jti @/home/j9build/workspace/Grinder/openjdk-tests/TestConfig/test_output_15711543632347/jck-runtime-lang_0/20191015-114603-Jck/results/JTB/stf_generated.jtb
```

So, I am hoping that, with this change in the JTI file, the new jck.extended build above will behave differently than the previous ones that hanged.

**Comment by JasonFengJ9** [comment]
The change for `jti` files only didn't fix `jdwp` timeout issue from an internal test.

**Comment by Mesbah-Alam** [comment]
We no longer need this PR as JCK 8-c update takes care of this.

**Pull request closed without merging**
