### PR TITLE
Remove check for osx when using dump optioons

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.ibm.com/runtimes/backlog/issues/284
Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
@JasonFengJ9  - please review.

**Comment by JasonFengJ9** [comment]
@Mesbah-Alam can we run a grinder for sanity check please?

**Comment by Mesbah-Alam** [comment]
Hi Jason, here's a sanity.jck run : https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/7668/console

**Comment by JasonFengJ9** [comment]
LGTM

**Pull request merged**
